version: '3.9'

services:
  postgresql:
    image: postgres:14.7
    container_name: postgresql
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: renat
      POSTGRES_PASSWORD: passwd
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=renat
      - --password=passwd
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbitmq:
    image:  rabbitmq:3.11.13-management
    container_name: rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
        - "5672:5672"
        - "15672:15672"        
    volumes:
        - rmq_data:/var/lib/rabbitmq
    networks:
        - backend
      
volumes:
  pg_data:
  rmq_data:

networks:
  backend:
  