scrape_configs:
  - job_name: 'bot_monitoring'
    metrics_path: /metrics
    scrape_interval: 4s
    static_configs:
        - targets:
            - "host.docker.internal:8092"

  - job_name: 'scrapper_monitoring'
    metrics_path: /metrics
    scrape_interval: 4s
    static_configs:
        - targets:
            - "host.docker.internal:8082"
