/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.LinkChat;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkChatRecord extends UpdatableRecordImpl<LinkChatRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINK_CHAT.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINK_CHAT.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LINK_CHAT.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINK_CHAT.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getChatId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return LinkChat.LINK_CHAT.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return LinkChat.LINK_CHAT.CHAT_ID;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Integer component2() {
        return getChatId();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Integer value2() {
        return getChatId();
    }

    @Override
    @NotNull
    public LinkChatRecord value1(@NotNull Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkChatRecord value2(@NotNull Integer value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkChatRecord values(@NotNull Integer value1, @NotNull Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkChatRecord
     */
    public LinkChatRecord() {
        super(LinkChat.LINK_CHAT);
    }

    /**
     * Create a detached, initialised LinkChatRecord
     */
    @ConstructorProperties({ "linkId", "chatId" })
    public LinkChatRecord(@NotNull Integer linkId, @NotNull Integer chatId) {
        super(LinkChat.LINK_CHAT);

        setLinkId(linkId);
        setChatId(chatId);
    }

    /**
     * Create a detached, initialised LinkChatRecord
     */
    public LinkChatRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.LinkChat value) {
        super(LinkChat.LINK_CHAT);

        if (value != null) {
            setLinkId(value.getLinkId());
            setChatId(value.getChatId());
        }
    }
}
