name: scrapperCI

env:
  DOCKER_IMAGE_NAME: scrapper-image:latest

on:
  push:
    paths:
      - '.github/workflows/scrapper.yml'
      - 'scrapper/**'
      - 'link-parser/**'
      - 'pom.xml'
      - 'checkstyle.xml'
      - '.editorconfig'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: maven

      - name: run docker-compose.yml
        run: docker-compose -f 'docker-compose.yml' up -d

      - name: maven package
        run: mvn package -pl scrapper -am

      - name: set lowercase repo name
        id: github_repo_lowercase
        run: echo "github_repo_lowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build scrapper module
        run: docker build --file scrapper/Dockerfile -t ghcr.io/${{ env.github_repo_lowercase }}/${{ env.DOCKER_IMAGE_NAME }} .

      - name: push docker image to GHCR
        run: docker push ghcr.io/${{ env.github_repo_lowercase }}/${{ env.DOCKER_IMAGE_NAME }}

  checkstyle:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: maven
      - name: run checkstyle
        run: mvn -pl scrapper -am checkstyle:check
